
project:
  type: website
  #output-dir: docs

website:
  title: "KNC-Website"
  favicon: favicon.ico
  description: "Official website for KNC services"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: services.qmd
        text: Services
      - href: about.qmd
        text: About
      - href: contact.qmd
        text: Contact

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    base-url: "/"   # << moved here
    code-line-numbers: true

editor: visual
