project:
  type: website
  output-dir: docs
  resources:
    - CNAME

website:
  title: "KNC-Website"
  site-url: "https://kingsneuroconsultants.com"  # Add this line
  favicon: favicon.ico
  description: "Official website for KNC services"

  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: patient-services.qmd
        text: "Patient Services"       # Clinical services with Dr. Hatice King
      - href: consultancy-services.qmd
        text: "Consultancy Services"  # Research/consultancy with Dr. Declan King
    right:
      - href: contact.qmd
        text: Contact

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    code-line-numbers: true
    base-url: "/"

editor: visual
